POST http://localhost:8080/events
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3OTExOTk3NjYsInVzZXJJZCI6MX0.c8OhoufjnnP0G5UpzU5EaB1J8cL-4uvQU_plA4W6NVI

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2026-09-30T09:55:00.000Z"
}
