POST http://localhost:8080/events
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3OTEyMTU0NjIsInVzZXJJZCI6MX0.9ogLv1LmqBIkXxin1Zlfs8HUxZUw66MNnK0ZNAxgdwo

{
    "name": "Another test event ",
    "description": "Birthday event!!",
    "location": "A test location",
    "dateTime": "2026-09-30T09:55:00.000Z"
}
