PUT http://localhost:8080/events/1
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3OTEyMTA2ODUsInVzZXJJZCI6MX0.JgWV5rxj1a-Zn8qAjpKzp_9wfza5CX_MmjCp0UvJ5p0

{
    "name": "updated test event",
    "description": "A test event", 
    "location": "Test location (Updated!)",
    "dateTime": "2026-09-30T15:15:00Z"
}